# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvillaes <mvillaes@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/20 15:02:59 by mvillaes          #+#    #+#              #
#    Updated: 2021/03/10 20:17:20 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -lmlx -framework OpenGL -framework AppKit main.c
	./a.out
	#& leaks a.out#

fclean:
	rm -rf ./a.out
