# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvillaes <mvillaes@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/20 15:02:59 by mvillaes          #+#    #+#              #
#    Updated: 2021/07/06 20:08:28 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -g -lmlx -framework OpenGL -framework AppKit test2.c
	./a.out
	
	#& leaks a.out

fclean:
	rm -rf ./a.out
