# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mvillaes <mvillaes@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/08/20 15:02:59 by mvillaes          #+#    #+#              #
#    Updated: 2021/07/14 21:14:56 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -g -Wall -Werror -Wextra -lmlx -framework OpenGL -framework AppKit 4keyimput.c
	
	#& leaks a.out

fclean:
	rm -rf ./a.out
